# Generated by Django 2.2.4 on 2019-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_experimental_setup', models.CharField(help_text='Currently selected experimental conditions', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_shortname', models.CharField(help_text='Enter field documentation', max_length=30)),
                ('comparisons', models.TextField(help_text='Enter the conditions separated by a comma.')),
                ('time_series', models.BooleanField()),
            ],
        ),
    ]
