# Generated by Django 2.2.3 on 2020-07-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_experimental_setup', models.CharField(help_text='Currently selected experimental conditions', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_shortname', models.CharField(help_text='Enter field documentation', max_length=30)),
                ('comparisons', models.TextField(help_text='Enter the conditions separated by a comma.')),
                ('time_series', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.CharField(help_text='TBD', max_length=160)),
                ('source_file', models.CharField(help_text='TBD', max_length=160)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='GeneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=60)),
                ('GO_annotation', models.CharField(default='NA', max_length=200)),
                ('gene_name', models.CharField(default='NA', max_length=200)),
                ('gene_description', models.CharField(default='NA', max_length=200)),
                ('gene_chrom', models.CharField(default='NA', max_length=200)),
                ('gene_ENS_protein', models.CharField(default='NA', max_length=60)),
                ('gene_ENS_transcript', models.CharField(default='NA', max_length=60)),
                ('gene_biotype', models.CharField(default='NA', max_length=60)),
                ('gene_strand', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PanelGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(help_text='Descriptor of panel', max_length=60)),
                ('phenotype', models.CharField(help_text='Phenotypic information', max_length=60)),
                ('gene_list', models.TextField(help_text='Comma separated list of gene IDs', max_length=10000)),
                ('bam_files', models.TextField(default='None', max_length=2000)),
                ('vcf_files', models.TextField(default='NA', max_length=2000)),
                ('comparison', models.CharField(default='None', max_length=160)),
                ('last_threshold', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=60)),
                ('gene_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GeneExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=60)),
                ('p_value', models.FloatField(null=True)),
                ('q_value', models.FloatField(null=True)),
                ('fold_change', models.FloatField(null=True)),
                ('expression_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.ExpressionSet')),
            ],
        ),
        migrations.CreateModel(
            name='ExonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exon_id', models.CharField(max_length=60)),
                ('exon_start', models.IntegerField(default=-1)),
                ('exon_stop', models.IntegerField(default=-1)),
                ('coverage', models.TextField(default='None', max_length=2000)),
                ('covOverThreshold', models.TextField(default='None', max_length=2000)),
                ('pb_coverage', models.TextField(default='None', max_length=1000000)),
                ('selected_cov', models.IntegerField(default=-1)),
                ('transcript_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.TranscriptInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CDSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cds_id', models.CharField(max_length=60)),
                ('protein_id', models.CharField(max_length=60)),
                ('cds_start', models.IntegerField(default=-1)),
                ('cds_stop', models.IntegerField(default=-1)),
                ('cds_frame', models.IntegerField(default=-1)),
                ('coverage', models.TextField(default='None', max_length=2000)),
                ('covOverThreshold', models.TextField(default='None', max_length=2000)),
                ('pb_coverage', models.TextField(default='None', max_length=1000000)),
                ('selected_cov', models.IntegerField(default=-1)),
                ('transcript_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.TranscriptInfo')),
            ],
        ),
    ]
