# Generated by Django 2.2.4 on 2019-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='geneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=60)),
                ('GO_annotation', models.CharField(default='NA', max_length=200)),
                ('gene_name', models.CharField(default='NA', max_length=200)),
                ('gene_ENS_protein', models.CharField(default='NA', max_length=60)),
                ('gene_ENS_transcript', models.CharField(default='NA', max_length=60)),
                ('gene_biotype', models.CharField(default='NA', max_length=60)),
                ('gene_strand', models.CharField(default='NA', max_length=10)),
                ('gene_exons', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='panelGeneList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(help_text='Descriptor of panel', max_length=60)),
                ('phenotype', models.CharField(help_text='Phenotypic information', max_length=60)),
                ('gene_list', models.CharField(help_text='Comma separated list of gene IDs', max_length=10000)),
            ],
        ),
    ]
