# Generated by Django 3.1.1 on 2021-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0002_geneinfo_gene_genome_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgenelist',
            name='reference_genome_used',
            field=models.CharField(default='None', max_length=160),
        ),
    ]
