# Generated by Django 2.2.4 on 2019-08-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0002_geneinfo_panelgenelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneinfo',
            name='gene_exons',
        ),
        migrations.AlterField(
            model_name='panelgenelist',
            name='gene_list',
            field=models.TextField(help_text='Comma separated list of gene IDs', max_length=10000),
        ),
        migrations.CreateModel(
            name='TranscriptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=60)),
                ('exon_positions', models.CharField(default='NA', max_length=10000)),
                ('gene_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exon_id', models.CharField(max_length=60)),
                ('exon_positions', models.CharField(default='NA', max_length=10000)),
                ('transcript_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.TranscriptInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CDSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cds_id', models.CharField(max_length=60)),
                ('protein_id', models.CharField(max_length=60)),
                ('cds_positions', models.CharField(default='NA', max_length=10000)),
                ('transcript_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.TranscriptInfo')),
            ],
        ),
    ]
