# Generated by Django 3.1.1 on 2021-10-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0003_panelgenelist_reference_genome_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(default='None', max_length=200)),
                ('phenotype_info', models.TextField(default='None', max_length=1000000)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.panelgenelist')),
            ],
        ),
    ]
