# Generated by Django 2.2.4 on 2019-08-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0004_auto_20190830_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptinfo',
            name='exon_positions',
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
