# Generated by Django 2.2.4 on 2019-08-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0005_auto_20190830_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdsinfo',
            name='cds_positions',
        ),
        migrations.RemoveField(
            model_name='exoninfo',
            name='exon_positions',
        ),
        migrations.AddField(
            model_name='cdsinfo',
            name='cds_frame',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='cdsinfo',
            name='cds_start',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='cdsinfo',
            name='cds_stop',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='exoninfo',
            name='exon_start',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='exoninfo',
            name='exon_stop',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
