# Generated by Django 2.2.4 on 2019-09-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0006_auto_20190830_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgenelist',
            name='bam_files',
            field=models.CharField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
