# Generated by Django 2.2.4 on 2019-09-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0009_auto_20190912_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneinfo',
            name='gene_chrom',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
