# Generated by Django 2.2.4 on 2019-09-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0011_auto_20190912_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdsinfo',
            old_name='cds_coverage',
            new_name='coverage',
        ),
        migrations.RenameField(
            model_name='exoninfo',
            old_name='exon_covOverThreshold',
            new_name='covOverThreshold',
        ),
        migrations.RenameField(
            model_name='exoninfo',
            old_name='exon_coverage',
            new_name='coverage',
        ),
        migrations.AddField(
            model_name='cdsinfo',
            name='covOverThreshold',
            field=models.TextField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
