# Generated by Django 2.2.4 on 2019-09-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_platform', '0014_auto_20190916_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelgenelist',
            name='last_threshold',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='transcriptinfo',
            name='gene_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_platform.GeneInfo'),
        ),
    ]
